apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJiV0Y0YVcxd0xXZG9PbWRvY0Y5aWRVOHphbVpFWlVkU2JWaHVkVUV3TldJeWIyRnJkMDh6V0haWVZWZ3lXalZNUW5BPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
